package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	classicYarnLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
		"# yarn lockfile v1\n\n\nlodash@^4.17.21:\n  version \"4.17.21\"\n"
	berryYarnLock = "# This file is generated by running \"yarn install\" inside your project.\n" +
		"# Manual changes might be lost - proceed with caution!\n\n" +
		"__metadata:\n  version: 8\n  cacheKey: 10c0\n\n" +
		"\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n"
)

func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// TestInstallCommandForRepo pins which install a repo shape earns. The
// npm-install fallbacks are not laziness: the build image ships neither pnpm
// nor a Berry-capable yarn, so for those shapes npm is the only thing that
// produces a working tree, and failing instead would break deploys that
// currently succeed.
func TestInstallCommandForRepo(t *testing.T) {
	cases := []struct {
		name       string
		files      map[string]string
		want       string
		wantReason bool
	}{
		{
			name:  "no lockfile — unchanged from before",
			files: map[string]string{"package.json": "{}"},
			want:  npmInstall,
		},
		{
			name:  "package-lock",
			files: map[string]string{"package.json": "{}", "package-lock.json": "{}"},
			want:  npmInstall,
		},
		{
			// The case that broke deployment-io/website-svc: .yarnrc
			// redirects yarn at a vendored Berry release, so the build
			// command runs Berry, which validates the project against
			// yarn.lock and rejects an npm-installed tree.
			name: "berry lockfile with a vendored release via .yarnrc",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-4.9.4.cjs\"\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			name: "berry lockfile with yarnPath in .yarnrc.yml",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			name: "berry lockfile with a release but no yarnPath",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			// Nothing in the image can run this: Classic cannot parse a
			// Berry lockfile. npm keeps the deploy alive, and the build
			// command's `yarn` resolves to Classic, which runs scripts
			// against an npm tree — which is how these repos have always
			// built here.
			name:       "berry lockfile, nothing pinning a berry binary",
			files:      map[string]string{"yarn.lock": berryYarnLock, "package.json": "{}"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:       "yarnPath naming a file that isn't there",
			files:      map[string]string{"yarn.lock": berryYarnLock, ".yarnrc.yml": "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:  "classic lockfile — the image's yarn understands it",
			files: map[string]string{"yarn.lock": classicYarnLock},
			want:  "yarn install",
		},
		{
			name:       "pnpm — no pnpm in the build image",
			files:      map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:       "pnpm wins over yarn and npm, still falls back",
			files:      map[string]string{"pnpm-lock.yaml": "x\n", "yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:  "yarn wins over npm",
			files: map[string]string{"yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			want:  "yarn install",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, reason := installCommandForRepo(writeRepo(t, tc.files))
			if got != tc.want {
				t.Errorf("install command = %q, want %q", got, tc.want)
			}
			if tc.wantReason && reason == "" {
				t.Error("a fallback must say why in the build log — the deploy " +
					"succeeds but the lockfile is being ignored, and silence hides that")
			}
		})
	}
}

// The ordinary npm repo must gain no narration it did not have before.
func TestInstallChoiceIsSilentForThePlainCase(t *testing.T) {
	var buf strings.Builder
	_, reason := installCommandForRepo(writeRepo(t, map[string]string{"package.json": "{}"}))
	logInstallChoice(&buf, reason)
	if buf.String() != "" {
		t.Errorf("plain npm repo logged %q, want nothing", buf.String())
	}
}

// A Classic lockfile is not Berry, and an empty or missing one is not either —
// misreading a Classic repo as Berry would send it down the fallback path and
// silently stop honouring its lockfile.
func TestYarnLockIsBerryAt(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{"berry", map[string]string{"yarn.lock": berryYarnLock}, true},
		{"classic", map[string]string{"yarn.lock": classicYarnLock}, false},
		{"absent", map[string]string{}, false},
		{"empty", map[string]string{"yarn.lock": ""}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := yarnLockIsBerryAt(writeRepo(t, tc.files)); got != tc.want {
				t.Errorf("yarnLockIsBerryAt() = %v, want %v", got, tc.want)
			}
		})
	}
}
