package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	classicYarnLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
		"# yarn lockfile v1\n\n\nlodash@^4.17.21:\n  version \"4.17.21\"\n"
	berryYarnLock = "# This file is generated by running \"yarn install\" inside your project.\n" +
		"# Manual changes might be lost - proceed with caution!\n\n" +
		"__metadata:\n  version: 8\n  cacheKey: 10c0\n\n" +
		"\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n"
)

func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// TestInstallCommandForRepo pins which install a repo shape earns. The
// npm-install fallbacks are not laziness: the build image ships neither pnpm
// nor a Berry-capable yarn, so for those shapes npm is the only thing that
// produces a working tree, and failing instead would break deploys that
// currently succeed.
func TestInstallCommandForRepo(t *testing.T) {
	cases := []struct {
		name string
		// buildCommand matters only for the PnP split; every other case is
		// decided by the tree alone, so they leave it at the common default.
		buildCommand string
		files        map[string]string
		want         string
		wantReason   bool
	}{
		{
			name:  "no lockfile — unchanged from before",
			files: map[string]string{"package.json": "{}"},
			want:  npmInstall,
		},
		{
			name:  "package-lock",
			files: map[string]string{"package.json": "{}", "package-lock.json": "{}"},
			want:  npmInstall,
		},
		{
			// The case that broke deployment-io/website-svc: .yarnrc
			// redirects yarn at a vendored Berry release, so the build
			// command runs Berry, which validates the project against
			// yarn.lock and rejects an npm-installed tree.
			name:         "berry lockfile with a vendored release via .yarnrc",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-4.9.4.cjs\"\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			name: "berry lockfile with yarnPath in .yarnrc.yml",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			name:         "berry lockfile with a release but no yarnPath",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			// Nothing in the image can run this: Classic cannot parse a
			// Berry lockfile. npm keeps the deploy alive, and the build
			// command's `yarn` resolves to Classic, which runs scripts
			// against an npm tree — which is how these repos have always
			// built here.
			name:       "berry lockfile, nothing pinning a berry binary",
			files:      map[string]string{"yarn.lock": berryYarnLock, "package.json": "{}"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:       "yarnPath naming a file that isn't there",
			files:      map[string]string{"yarn.lock": berryYarnLock, ".yarnrc.yml": "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			// website-svc's shape until 2026-08-28, and the regression this
			// nearly shipped: `yarn policies set-version` on Yarn 1 vendors a
			// CLASSIC release and writes the same .yarnrc redirect a Berry repo
			// uses. Choosing yarn here sends a Berry lockfile to Classic, which
			// aborts — breaking a deploy that works today under npm.
			name: "berry lockfile with a vendored CLASSIC release",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-1.22.1.js\"\n",
				".yarn/releases/yarn-1.22.1.js": "// yarn 1\n",
			},
			want:       npmInstall,
			wantReason: true,
		},
		{
			// A Classic lockfile with a Classic vendored release is the
			// consistent Yarn 1 repo — yarn reads its own lockfile fine.
			name: "classic lockfile with a vendored classic release",
			files: map[string]string{
				"yarn.lock":                     classicYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-1.22.1.js\"\n",
				".yarn/releases/yarn-1.22.1.js": "// yarn 1\n",
			},
			want: "yarn install",
		},
		{
			// Unrecognized filename means undetermined, and undetermined must
			// mean "not Berry" — guessing Berry hands the lockfile to a yarn
			// that may not read it, which is a failed deploy.
			name: "berry lockfile with a release whose name carries no version",
			files: map[string]string{
				"yarn.lock":               berryYarnLock,
				".yarnrc.yml":             "yarnPath: .yarn/releases/yarn.cjs\n",
				".yarn/releases/yarn.cjs": "// yarn ?\n",
			},
			want:       npmInstall,
			wantReason: true,
		},
		{
			// packageManager is NOT a pin here: the build image has no enabled
			// corepack, so nothing reads it and yarn stays Classic.
			name: "berry lockfile with only a packageManager field",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
			},
			want:       npmInstall,
			wantReason: true,
		},
		// Plug'n'Play is the Yarn 2+ DEFAULT — no nodeLinker means no
		// node_modules — so which install is correct depends on how the build
		// is invoked. Both directions are live, which is why the build command
		// is consulted at all.
		{
			name:         "PnP with a yarn build command",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			// Broken by a yarn install: PnP leaves no node_modules for
			// `next build` to resolve through. npm is what works today.
			name:         "PnP with a non-yarn build command",
			buildCommand: "next build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want:       npmInstall,
			wantReason: true,
		},
		{
			// node-modules linker means the tree suits any build command.
			name:         "node-modules linker with a non-yarn build command",
			buildCommand: "npm run build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			// Chained commands still count as running through yarn.
			name:         "PnP with yarn later in a chained build command",
			buildCommand: "echo building && yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			want: "yarn install",
		},
		{
			name:  "classic lockfile — the image's yarn understands it",
			files: map[string]string{"yarn.lock": classicYarnLock},
			want:  "yarn install",
		},
		{
			name:       "pnpm — no pnpm in the build image",
			files:      map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:       "pnpm wins over yarn and npm, still falls back",
			files:      map[string]string{"pnpm-lock.yaml": "x\n", "yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			want:       npmInstall,
			wantReason: true,
		},
		{
			name:  "yarn wins over npm",
			files: map[string]string{"yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			want:  "yarn install",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, reason := installCommandForRepo(writeRepo(t, tc.files), tc.buildCommand)
			if got != tc.want {
				t.Errorf("install command = %q, want %q", got, tc.want)
			}
			if tc.wantReason && reason == "" {
				t.Error("a fallback must say why in the build log — the deploy " +
					"succeeds but the lockfile is being ignored, and silence hides that")
			}
		})
	}
}

// The ordinary npm repo must gain no narration it did not have before.
func TestInstallChoiceIsSilentForThePlainCase(t *testing.T) {
	var buf strings.Builder
	_, reason := installCommandForRepo(writeRepo(t, map[string]string{"package.json": "{}"}), "npm run build")
	logInstallChoice(&buf, reason)
	if buf.String() != "" {
		t.Errorf("plain npm repo logged %q, want nothing", buf.String())
	}
}

// A Classic lockfile is not Berry, and an empty or missing one is not either —
// misreading a Classic repo as Berry would send it down the fallback path and
// silently stop honouring its lockfile.
func TestYarnLockIsBerryAt(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{"berry", map[string]string{"yarn.lock": berryYarnLock}, true},
		{"classic", map[string]string{"yarn.lock": classicYarnLock}, false},
		{"absent", map[string]string{}, false},
		{"empty", map[string]string{"yarn.lock": ""}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := yarnLockIsBerryAt(writeRepo(t, tc.files)); got != tc.want {
				t.Errorf("yarnLockIsBerryAt() = %v, want %v", got, tc.want)
			}
		})
	}
}
