package commands

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const (
	classicYarnLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
		"# yarn lockfile v1\n\n\nlodash@^4.17.21:\n  version \"4.17.21\"\n"
	berryYarnLock = "# This file is generated by running \"yarn install\" inside your project.\n" +
		"# Manual changes might be lost - proceed with caution!\n\n" +
		"__metadata:\n  version: 8\n  cacheKey: 10c0\n\n" +
		"\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n"
)

func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// TestInstallPlanForRepo pins which install a repo shape earns: the manager,
// the frozen flag, and whether a corepack shim has to be enabled first.
//
// The frozen command is asserted per case rather than derived, because the
// per-manager flags are the thing most likely to be "fixed" into each other by
// someone working from memory — Yarn Classic accepts Berry's `--immutable`
// without complaint and installs permissively anyway, so a swap there fails no
// test that only checks the exit status of a build.
//
// The npm-install fallbacks are not laziness: for those shapes there is no
// binary that can read the lockfile, and failing instead would break deploys
// that currently succeed.
func TestInstallPlanForRepo(t *testing.T) {
	cases := []struct {
		name string
		// buildCommand matters only for the Plug'n'Play split; every other case
		// is decided by the tree alone, so they leave it at the common default.
		buildCommand   string
		files          map[string]string
		wantManager    string
		wantFrozen     string
		wantPermissive string
		wantCorepack   string
		wantReason     bool
	}{
		{
			name:           "no lockfile — nothing to freeze against",
			files:          map[string]string{"package.json": "{}"},
			wantManager:    "npm",
			wantPermissive: npmInstall,
		},
		{
			name:           "package-lock",
			files:          map[string]string{"package.json": "{}", "package-lock.json": "{}"},
			wantManager:    "npm",
			wantFrozen:     npmFrozen,
			wantPermissive: npmInstall,
		},
		{
			// npm ci reads a shrinkwrap the same way, and a repo that ships one
			// is asking for exactly this.
			name:           "npm-shrinkwrap",
			files:          map[string]string{"package.json": "{}", "npm-shrinkwrap.json": "{}"},
			wantManager:    "npm",
			wantFrozen:     npmFrozen,
			wantPermissive: npmInstall,
		},
		{
			name:           "classic lockfile — the image's yarn understands it",
			files:          map[string]string{"yarn.lock": classicYarnLock},
			wantManager:    "yarn",
			wantFrozen:     yarnClassicFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// The pin is Classic, so the flag must stay Classic's even though
			// corepack is now involved.
			name: "classic lockfile pinned to a classic yarn",
			files: map[string]string{
				"yarn.lock":    classicYarnLock,
				"package.json": `{"packageManager":"yarn@1.22.22"}`,
			},
			wantManager:    "yarn",
			wantFrozen:     yarnClassicFrozen,
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// The gap #115 left, and the reason this change exists: a
			// packageManager pin with no vendored release used to fall back to
			// npm because nothing read the field.
			name:         "berry lockfile pinned only by packageManager",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// A corepack-fetched Berry is still Berry: PnP writes no
			// node_modules, so #115's build-command split applies here too.
			name:         "berry pinned by packageManager, PnP, non-yarn build",
			buildCommand: "next build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			name:         "berry pinned by packageManager, node-modules linker, non-yarn build",
			buildCommand: "next build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
				".yarnrc.yml":  "nodeLinker: node-modules\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// A Berry binary migrates a Classic lockfile as it installs, so a
			// frozen install would abort on a repo that is mid-migration rather
			// than drifted. Permissive, and the log says why.
			name:         "classic lockfile with a berry pin",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":    classicYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
			},
			wantManager:    "yarn",
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// The case that broke deployment-io/website-svc: .yarnrc redirects
			// yarn at a vendored Berry release, so the build command runs Berry,
			// which validates the project against yarn.lock and rejects an
			// npm-installed tree. The release runs whatever corepack would have
			// picked, so no shim is enabled.
			name:         "berry lockfile with a vendored release via .yarnrc",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-4.9.4.cjs\"\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			name: "berry lockfile with yarnPath in .yarnrc.yml",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			name:         "berry lockfile with a release but no yarnPath",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// A vendored release wins over a pin because it wins at runtime:
			// the .yarnrc redirect is what the yarn on the PATH obeys.
			name:         "vendored release outranks a conflicting packageManager pin",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				"package.json":                  `{"packageManager":"yarn@3.6.4"}`,
				".yarnrc.yml":                   "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// website-svc's shape until 2026-08-28, and the regression this
			// nearly shipped: `yarn policies set-version` on Yarn 1 vendors a
			// CLASSIC release and writes the same .yarnrc redirect a Berry repo
			// uses. Choosing yarn here sends a Berry lockfile to Classic, which
			// aborts — breaking a deploy that works today under npm.
			name: "berry lockfile with a vendored CLASSIC release",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-1.22.1.js\"\n",
				".yarn/releases/yarn-1.22.1.js": "// yarn 1\n",
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			// A pin can be Classic too, and then it cannot read a Berry
			// lockfile any more than the image's yarn could.
			name: "berry lockfile pinned to a classic yarn",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@1.22.22"}`,
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			name:           "berry lockfile, nothing pinning a berry binary",
			files:          map[string]string{"yarn.lock": berryYarnLock, "package.json": "{}"},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			name:           "yarnPath naming a file that isn't there",
			files:          map[string]string{"yarn.lock": berryYarnLock, ".yarnrc.yml": "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n"},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			// Unrecognized filename means undetermined, and undetermined must
			// mean "not Berry" — guessing Berry hands the lockfile to a yarn
			// that may not read it, which is a failed deploy.
			name: "berry lockfile with a release whose name carries no version",
			files: map[string]string{
				"yarn.lock":               berryYarnLock,
				".yarnrc.yml":             "yarnPath: .yarn/releases/yarn.cjs\n",
				".yarn/releases/yarn.cjs": "// yarn ?\n",
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			// A Classic lockfile with a Classic vendored release is the
			// consistent Yarn 1 repo — yarn reads its own lockfile fine.
			name: "classic lockfile with a vendored classic release",
			files: map[string]string{
				"yarn.lock":                     classicYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-1.22.1.js\"\n",
				".yarn/releases/yarn-1.22.1.js": "// yarn 1\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnClassicFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// Chained commands still count as running through yarn.
			name:         "PnP with yarn later in a chained build command",
			buildCommand: "echo building && yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc.yml":                   "yarnPath: .yarn/releases/yarn-4.9.4.cjs\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// Berry does not read .npmrc, so a repo whose private registry
			// lives only there installs today under npm and would fail under
			// the Berry this change would otherwise newly select.
			name:         "berry pin with private registry auth only in .npmrc",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
				".npmrc":       "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}\n@acme:registry=https://npm.pkg.github.com\n",
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			// The same repo once .yarnrc.yml carries the same settings in the
			// form Berry reads.
			name:         "berry pin with the registry migrated to .yarnrc.yml",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
				".npmrc":       "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}\n",
				".yarnrc.yml":  "npmScopes:\n  acme:\n    npmRegistryServer: \"https://npm.pkg.github.com\"\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// An .npmrc of ordinary knobs is not registry configuration and
			// must not cost the repo its yarn install.
			name:         "berry pin with a harmless .npmrc",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":    berryYarnLock,
				"package.json": `{"packageManager":"yarn@4.9.4"}`,
				".npmrc":       "# our defaults\nengine-strict=true\nsave-exact=true\nregistry=https://registry.npmjs.org/\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantCorepack:   "yarn",
			wantReason:     true,
		},
		{
			// The .npmrc guard covers repos this change newly routes into
			// Berry. A repo that already ran Berry through a vendored release
			// is not one of them, and quietly demoting it to npm would be this
			// change breaking a working deploy.
			name:         "vendored berry release with auth only in .npmrc is left alone",
			buildCommand: "yarn build",
			files: map[string]string{
				"yarn.lock":                     berryYarnLock,
				".yarnrc":                       "yarn-path \".yarn/releases/yarn-4.9.4.cjs\"\n",
				".yarn/releases/yarn-4.9.4.cjs": "// yarn 4\n",
				".npmrc":                        "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}\n",
			},
			wantManager:    "yarn",
			wantFrozen:     yarnBerryFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
		{
			// The other half of the change: pnpm now actually runs.
			name:           "pnpm",
			files:          map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"},
			wantManager:    "pnpm",
			wantFrozen:     pnpmFrozen,
			wantPermissive: pnpmInstall,
			wantCorepack:   "pnpm",
			wantReason:     true,
		},
		{
			name: "pnpm pinned by packageManager",
			files: map[string]string{
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
				"package.json":   `{"packageManager":"pnpm@10.4.1+sha512.abc123"}`,
			},
			wantManager:    "pnpm",
			wantFrozen:     pnpmFrozen,
			wantPermissive: pnpmInstall,
			wantCorepack:   "pnpm",
			wantReason:     true,
		},
		{
			// Corepack refuses to run pnpm in a project pinned to yarn, so
			// there is no pnpm to be had and npm keeps the deploy alive.
			name: "pnpm lockfile in a repo pinned to yarn",
			files: map[string]string{
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
				"package.json":   `{"packageManager":"yarn@4.9.4"}`,
			},
			wantManager:    "npm",
			wantPermissive: npmInstall,
			wantReason:     true,
		},
		{
			name:           "pnpm wins over yarn and npm",
			files:          map[string]string{"pnpm-lock.yaml": "x\n", "yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			wantManager:    "pnpm",
			wantFrozen:     pnpmFrozen,
			wantPermissive: pnpmInstall,
			wantCorepack:   "pnpm",
			wantReason:     true,
		},
		{
			name:           "yarn wins over npm",
			files:          map[string]string{"yarn.lock": classicYarnLock, "package-lock.json": "{}"},
			wantManager:    "yarn",
			wantFrozen:     yarnClassicFrozen,
			wantPermissive: yarnInstall,
			wantReason:     true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := planInstall(writeRepo(t, tc.files), tc.buildCommand)
			if p.manager != tc.wantManager {
				t.Errorf("manager = %q, want %q", p.manager, tc.wantManager)
			}
			if p.frozen != tc.wantFrozen {
				t.Errorf("frozen install = %q, want %q", p.frozen, tc.wantFrozen)
			}
			if p.permissive != tc.wantPermissive {
				t.Errorf("permissive install = %q, want %q", p.permissive, tc.wantPermissive)
			}
			if p.corepack != tc.wantCorepack {
				t.Errorf("corepack shim = %q, want %q", p.corepack, tc.wantCorepack)
			}
			if tc.wantReason && p.reason == "" {
				t.Error("this shape must say what it chose in the build log — a deploy " +
					"that succeeds while ignoring a lockfile is the failure mode that hid all of this")
			}
			if !tc.wantReason && p.reason != "" {
				t.Errorf("the ordinary npm repo gained narration it never had: %q", p.reason)
			}
			if p.frozen != "" && p.drift == "" {
				t.Error("a frozen install with no drift marker cannot tell a stale lockfile " +
					"from a real failure, which is the whole basis of the fallback")
			}
		})
	}
}

// The frozen install must fall back ONLY on lockfile drift. Every other
// failure has to stay failed: a permissive retry that "recovers" from a
// network blip or a broken postinstall is how a broken install becomes a
// silent one again.
func TestFrozenInstallFallsBackOnDriftAndNothingElse(t *testing.T) {
	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the install command is bash-only by construction")
	}
	repo := writeRepo(t, map[string]string{"package.json": "{}", "package-lock.json": "{}"})
	command, _ := installCommandForRepo(repo, "npm run build")
	// Stub npm: the first call fails with the output under test, the second
	// (the permissive fallback, if it runs) leaves a marker behind.
	dir := t.TempDir()
	marker := filepath.Join(dir, "permissive-ran")
	cases := []struct {
		name         string
		output       string
		wantFallback bool
	}{
		{
			name: "drift",
			output: "npm error `npm ci` can only install packages when your package.json and package-lock.json " +
				"or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.",
			wantFallback: true,
		},
		{name: "network failure", output: "npm error network request to https://registry.npmjs.org/lodash failed"},
		{name: "failing postinstall", output: "npm error command sh -c node-gyp rebuild\nnpm error gyp ERR! build error"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			os.Remove(marker)
			stub := "#!/bin/bash\nif [ \"$1\" = ci ]; then echo " + shellQuote(tc.output) + "; exit 1; fi\ntouch " + marker + "\n"
			if err := os.WriteFile(filepath.Join(dir, "npm"), []byte(stub), 0o755); err != nil {
				t.Fatal(err)
			}
			cmd := exec.Command(bash, "-c", command)
			cmd.Env = append(os.Environ(), "PATH="+dir+string(os.PathListSeparator)+os.Getenv("PATH"))
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("install command exited %v; output:\n%s", err, out)
			}
			_, statErr := os.Stat(marker)
			if ranFallback := statErr == nil; ranFallback != tc.wantFallback {
				t.Errorf("permissive fallback ran = %v, want %v; output:\n%s", ranFallback, tc.wantFallback, out)
			}
			if tc.wantFallback && !strings.Contains(string(out), "NOT reproducible") {
				t.Errorf("the drift fallback must be loud about what it did; got:\n%s", out)
			}
		})
	}
}

// Every install command is a shell program now, and a syntax error in one is a
// syntax error in every deploy of that shape. `bash -n` on the exact string
// build_static_site.go hands the container — install, newline, build command —
// is the cheapest way to keep that from shipping.
func TestInstallCommandIsValidShell(t *testing.T) {
	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the install command is bash-only by construction")
	}
	repos := map[string]map[string]string{
		"npm":              {"package.json": "{}"},
		"npm with lock":    {"package.json": "{}", "package-lock.json": "{}"},
		"yarn classic":     {"yarn.lock": classicYarnLock},
		"yarn berry pin":   {"yarn.lock": berryYarnLock, "package.json": `{"packageManager":"yarn@4.9.4"}`},
		"yarn classic pin": {"yarn.lock": classicYarnLock, "package.json": `{"packageManager":"yarn@1.22.22"}`},
		"pnpm":             {"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"},
	}
	for name, files := range repos {
		t.Run(name, func(t *testing.T) {
			command, _ := installCommandForRepo(writeRepo(t, files), "yarn build")
			full := command + "\n" + "next build && echo done"
			cmd := exec.Command(bash, "-n")
			cmd.Stdin = strings.NewReader(full)
			if out, err := cmd.CombinedOutput(); err != nil {
				t.Errorf("bash rejected the install command: %v\n%s\n--- command ---\n%s", err, out, full)
			}
		})
	}
}

// A corepack path must degrade rather than explode: if the image has no
// corepack, or nowhere writable to put a shim, the deploy falls back to what it
// did before corepack existed and says so in the log.
func TestCorepackFallbackWhenTheImageHasNone(t *testing.T) {
	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the install command is bash-only by construction")
	}
	repo := writeRepo(t, map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"})
	command, _ := installCommandForRepo(repo, "next build")
	dir := t.TempDir()
	// A corepack that cannot enable anything (read-only install dir, or no
	// corepack at all, both land here) and an npm that records that it ran.
	if err := os.WriteFile(filepath.Join(dir, "corepack"), []byte("#!/bin/bash\nexit 1\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(dir, "npm-ran")
	if err := os.WriteFile(filepath.Join(dir, "npm"), []byte("#!/bin/bash\ntouch "+marker+"\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(bash, "-c", command)
	cmd.Env = append(os.Environ(), "PATH="+dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("install command exited %v; output:\n%s", err, out)
	}
	if _, err := os.Stat(marker); err != nil {
		t.Errorf("npm did not run as the no-corepack fallback; output:\n%s", out)
	}
	if !strings.Contains(string(out), "corepack is not available") {
		t.Errorf("losing corepack must be loud, not silent; output:\n%s", out)
	}
}

// The ordinary npm repo must gain no narration it did not have before.
func TestInstallChoiceIsSilentForThePlainCase(t *testing.T) {
	var buf strings.Builder
	_, reason := installCommandForRepo(writeRepo(t, map[string]string{"package.json": "{}"}), "npm run build")
	logInstallChoice(&buf, reason)
	if buf.String() != "" {
		t.Errorf("plain npm repo logged %q, want nothing", buf.String())
	}
}

// packageManager is what corepack reads, so misreading it selects the wrong
// binary — or, for a hash-suffixed pin, no binary at all.
func TestPackageManagerPin(t *testing.T) {
	cases := []struct {
		name             string
		files            map[string]string
		manager, version string
	}{
		{"yarn", map[string]string{"package.json": `{"packageManager":"yarn@4.9.4"}`}, "yarn", "4.9.4"},
		{
			"with corepack's integrity suffix",
			map[string]string{"package.json": `{"packageManager":"pnpm@10.4.1+sha512.deadbeef"}`},
			"pnpm", "10.4.1",
		},
		{"npm", map[string]string{"package.json": `{"packageManager":"npm@10.9.0"}`}, "npm", "10.9.0"},
		{"absent", map[string]string{"package.json": `{"name":"site"}`}, "", ""},
		{"no package.json", map[string]string{}, "", ""},
		{"malformed json", map[string]string{"package.json": "{not json"}, "", ""},
		{"no version", map[string]string{"package.json": `{"packageManager":"yarn"}`}, "", ""},
		{"a manager corepack does not proxy", map[string]string{"package.json": `{"packageManager":"bun@1.1.0"}`}, "", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			manager, version := packageManagerPin(writeRepo(t, tc.files))
			if manager != tc.manager || version != tc.version {
				t.Errorf("packageManagerPin() = (%q, %q), want (%q, %q)", manager, version, tc.manager, tc.version)
			}
		})
	}
}

// A Classic lockfile is not Berry, and an empty or missing one is not either —
// misreading a Classic repo as Berry would send it down the fallback path and
// silently stop honouring its lockfile.
func TestYarnLockIsBerryAt(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{"berry", map[string]string{"yarn.lock": berryYarnLock}, true},
		{"classic", map[string]string{"yarn.lock": classicYarnLock}, false},
		{"absent", map[string]string{}, false},
		{"empty", map[string]string{"yarn.lock": ""}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := yarnLockIsBerryAt(writeRepo(t, tc.files)); got != tc.want {
				t.Errorf("yarnLockIsBerryAt() = %v, want %v", got, tc.want)
			}
		})
	}
}
