# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: deployment-runner
    main: ./entrypoints/local
    ldflags:
      - -s -w -X main.version={{.Version}}
      - '-s -w -X "main.clientCertPem={{.Env.TLS_CERT}}"'
      - '-s -w -X "main.clientKeyPem={{.Env.TLS_KEY}}"'
      - -s -w -X main.serviceFromBuild={{.Env.SERVICE}}

  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    binary: deployment-runner
    main: ./entrypoints/local
    ldflags:
      - -s -w -X main.version={{.Version}}
      - '-s -w -X "main.clientCertPem={{.Env.TLS_CERT}}"'
      - '-s -w -X "main.clientKeyPem={{.Env.TLS_KEY}}"'
      - -s -w -X main.serviceFromBuild={{.Env.SERVICE}}

  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/osxcross/target/bin/oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    binary: deployment-runner
    main: ./entrypoints/local
    ldflags:
      - -s -w -X main.version={{.Version}}
      - '-s -w -X "main.clientCertPem={{.Env.TLS_CERT}}"'
      - '-s -w -X "main.clientKeyPem={{.Env.TLS_KEY}}"'
      - -s -w -X main.serviceFromBuild={{.Env.SERVICE}}

  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    binary: deployment-runner
    main: ./entrypoints/local
    ldflags:
      - -s -w -X main.version={{.Version}}
      - '-s -w -X "main.clientCertPem={{.Env.TLS_CERT}}"'
      - '-s -w -X "main.clientKeyPem={{.Env.TLS_KEY}}"'
      - -s -w -X main.serviceFromBuild={{.Env.SERVICE}}

archives:
  - format: tar.gz
    name_template: "deployment-runner_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
